/*
Copyright (c) 2023 KylinSoft Co., Ltd.
Kylin trusted image builder(ktib) is licensed under Mulan PSL v2.
You can use this software according to the terms and conditions of the Mulan PSL v2.
You may obtain a copy of Mulan PSL v2 at:

	http://license.coscl.org.cn/MulanPSL2

THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING
BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
See the Mulan PSL v2 for more details.
*/
package templates

const RemoveList = `# at-spi2-atk
at-spi2-core
autogen
avahi-libs
cairo
colord-libs
cups-libs
dconf
diffutils
dnf-help
dracut
e2fsprogs-help
fontconfig
freetype
fuse-help
gcr
gdk-pixbuf2
gpg-pubkey
groff
grub2-common
grub2-tools
grub2-tools-minimal
gtk2
gtk3
guile
hardlink
harfbuzz
hicolor-icon-theme
kpartx
kylin-rpm-config
libevent
libjpeg-turbo
libnetfilter_conntrack
libnfnetlink
libproxy
libreport
libseccomp-help
libsecret
libsoup
libssh-help
libtiff
libX11
libXau
libXaw
libXcomposite
libXcursor
libXdamage
libXext
libXfixes
libXft
libXi
libXinerama
libxkbcommon
libxml2-help
libXmu
libXrandr
libXrender
libXt
libXtst
man-db
mozjs52
multipath-tools-help
newt
openssl
openssl-pkcs11
pango
perl
perl-Algorithm-Diff
perl-Archive-Tar
perl-autodie
perl-B-Debug
perl-bignum
perl-Carp
perl-Compress-Raw-Bzip2
perl-Compress-Raw-Zlib
perl-Config-Perl-V
perl-constant
perl-CPAN-Meta
perl-CPAN-Meta-Requirements
perl-CPAN-Meta-YAML
perl-Data-Dumper
perl-DB_File
perl-devel
perl-Devel-PPPort
perl-Digest
perl-Digest-MD5
perl-Digest-SHA
perl-Encode
perl-Encode-devel
perl-Env
perl-experimental
perl-Exporter
perl-ExtUtils-Command
perl-ExtUtils-Install
perl-ExtUtils-MakeMaker
perl-ExtUtils-Manifest
perl-ExtUtils-ParseXS
perl-File-Fetch
perl-File-HomeDir
perl-File-Path
perl-File-Temp
perl-File-Which
perl-Filter
perl-Filter-Simple
perl-Getopt-Long
perl-HTTP-Tiny
perl-IO-Compress
perl-IO-Socket-IP
perl-IPC-Cmd
perl-IPC-System-Simple
perl-IPC-SysV
perl-JSON-PP
perl-libnet
perl-libs
perl-Locale-Codes
perl-Locale-Maketext
perl-Math-BigInt
perl-Math-BigInt-FastCalc
perl-Math-BigRat
perl-MIME-Base64
perl-Module-CoreList
perl-Module-Load
perl-Module-Load-Conditional
perl-Module-Metadata
perl-Params-Check
perl-parent
perl-PathTools
perl-perlfaq
perl-PerlIO-via-QuotedPrint
perl-Perl-OSType
perl-Pod-Checker
perl-Pod-Escapes
perl-podlators
perl-Pod-Parser
perl-Pod-Perldoc
perl-Pod-Simple
perl-Pod-Usage
perl-Scalar-List-Utils
perl-Socket
perl-Storable
perl-Sys-Syslog
perl-Term-ANSIColor
perl-Term-Cap
perl-Test-Harness
perl-Test-Simple
perl-Text-Balanced
perl-Text-Diff
perl-Text-ParseWords
perl-Text-Tabs+Wrap
perl-Thread-Queue
perl-threads
perl-threads-shared
perl-Time-HiRes
perl-Time-Local
perl-Unicode-Collate
perl-Unicode-Normalize
perl-version
pigz
pinentry
pixman
pkgconf
python3-cairo
qt5-srpm-macros
rest
slang
trousers
unbound-libs
wayland
xkeyboard-config
xmlrpc-c
NetworkManager-libnm abattis-cantarell-fonts adobe-source-code-pro-fonts adwaita-icon-theme atk dbus fonts-filesystem fribidi glib-networking glibc-all-langpacks graphite2 gsettings-desktop-schemas jbigkit-libs json-glib lcms2 libdatrie libepoxy libgusb libicu libthai libusbx libxcb
`
